# Generated by Django 5.0.3 on 2024-03-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(default='', max_length=255)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=255)),
                ('isCorreta', models.BooleanField(blank=True, default=False, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questao')),
            ],
        ),
    ]
