# Generated by Django 5.0.3 on 2024-03-24 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
    ]
