# Generated by Django 5.0.3 on 2024-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_topico_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tempo_leitura',
            field=models.CharField(default='30', max_length=2),
        ),
    ]
